# AdWordsClient configurations
adwords:
  #############################################################################
  # Required Fields                                                           #
  #############################################################################
  developer_token: 7WZIpOrPxQ--dmFNS7b9Iw
  user_agent: nearbuy.com:AdWordsPOC:V0.1
  #############################################################################
  # Optional Fields                                                           #
  #############################################################################
  
  client_customer_id: 209-273-9606
  #client_customer_id: 303-897-7265
  #client_customer_id: 172-589-4812

  # partial_failure: True
  # validate_only: True
  #############################################################################
  # OAuth2 Configuration                                                   #
  # Below you may provide credentials for either the installed application or #
  # service account flows. Remove or comment the lines for the flow you're    #
  # not using.                                                                #
  #############################################################################
  # The following values configure the client for the installed application
  # flow.
  client_id: 114720141233-au9ij6rvk3e532mnqe2g2nvstubu8ku1.apps.googleusercontent.com
  client_secret: AAsWf8TO4medwNyhUHEm2mm2
  refresh_token: 1/463w2fUeWmEwhRFzVQ0In7CXrq3CXAG3PhtNy3XdHdg
  # The following values configure the client for the service account flow.
  # service_account_email: INSERT_SERVICE_ACCOUNT_EMAIL_HERE
  # path_to_private_key_file: INSERT_PATH_TO_FILE_HERE
  #############################################################################
  # ReportDownloader Headers                                                  #
  # Below you may specify boolean values for optional headers that will be    #
  # applied to all requests made by the ReportDownloader utility by default.  #
  #############################################################################
  # report_downloader_headers:
    # skip_report_header: False
    # skip_column_header: False
    # skip_report_summary: False
    # use_raw_enum_values: False


# DfpClient configurations
dfp:
  #############################################################################
  # Required Fields                                                           #
  #############################################################################
  application_name: INSERT_APPLICATION_NAME_HERE
  # The following values are required for all services except NetworkService,
  # unless the network code is set directly on the DfpClient object:
  # network_code: INSERT_NETWORK_CODE_HERE
  #############################################################################
  # OAuth2 Configuration                                                   #
  # Below you may provide credentials for either the installed application or #
  # service account flows. Remove or comment the lines for the flow you're    #
  # not using.                                                                #
  #############################################################################
  # The following values configure the client for the installed application
  # flow.
  client_id: INSERT_OAUTH_2_CLIENT_ID_HERE
  client_secret: INSERT_CLIENT_SECRET_HERE
  refresh_token: INSERT_REFRESH_TOKEN_HERE
  # The following values configure the client for the service account flow.
  # service_account_email: INSERT_SERVICE_ACCOUNT_EMAIL_HERE
  # path_to_private_key_file: INSERT_PATH_TO_FILE_HERE


# Proxy configurations (optional)
# proxy_config:
  # If specified, the given cafile will only be used if certificate validation
  # is not disabled.
  # cafile: INSERT_PATH_HERE
  # disable_certificate_validation: False
  # http_proxy:
    # host: INSERT_HOST_HERE
    # port: INSERT_PROXY_PORT_HERE
    # The following values are optional:
    # username: INSERT_USERNAME_HERE
    # password: INSERT_PASSWORD_HERE
  # https_proxy:
    # host: INSERT_HOST_HERE
    # port: INSERT_PROXY_PORT_HERE
    # The following values are optional:
    # username: INSERT_USERNAME_HERE
    # password: INSERT_PASSWORD_HERE
